import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        brand: ["'Antique Olive'", "Impact", "Arial Black", "sans-serif"],
        ui:    ["'Inter'", "sans-serif"],
        body:  ["'DM Sans'", "'Inter'", "sans-serif"],
      },
      colors: {
        border:     "hsl(var(--border))",
        input:      "hsl(var(--input))",
        ring:       "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT:    "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT:    "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT:    "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT:    "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT:    "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT:    "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT:    "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT:              "hsl(var(--sidebar-background))",
          foreground:           "hsl(var(--sidebar-foreground))",
          primary:              "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent:               "hsl(var(--sidebar-accent))",
          "accent-foreground":  "hsl(var(--sidebar-accent-foreground))",
          border:               "hsl(var(--sidebar-border))",
          ring:                 "hsl(var(--sidebar-ring))",
        },
        /* ── KM0 LAB palette ───────────────────────────────── */
        "km0-blue": {
          50:  "hsl(var(--km0-blue-50))",
          100: "hsl(var(--km0-blue-100))",
          200: "hsl(var(--km0-blue-200))",
          300: "hsl(var(--km0-blue-300))",
          400: "hsl(var(--km0-blue-400))",
          500: "hsl(var(--km0-blue-500))",
          600: "hsl(var(--km0-blue-600))",
          700: "hsl(var(--km0-blue-700))",
          800: "hsl(var(--km0-blue-800))",
          900: "hsl(var(--km0-blue-900))",
        },
        "km0-beige": {
          50:  "hsl(var(--km0-beige-50))",
          100: "hsl(var(--km0-beige-100))",
          200: "hsl(var(--km0-beige-200))",
          300: "hsl(var(--km0-beige-300))",
          400: "hsl(var(--km0-beige-400))",
          500: "hsl(var(--km0-beige-500))",
          600: "hsl(var(--km0-beige-600))",
          700: "hsl(var(--km0-beige-700))",
          800: "hsl(var(--km0-beige-800))",
          900: "hsl(var(--km0-beige-900))",
        },
        "km0-yellow": {
          50:  "hsl(var(--km0-yellow-50))",
          100: "hsl(var(--km0-yellow-100))",
          200: "hsl(var(--km0-yellow-200))",
          300: "hsl(var(--km0-yellow-300))",
          400: "hsl(var(--km0-yellow-400))",
          500: "hsl(var(--km0-yellow-500))",
          600: "hsl(var(--km0-yellow-600))",
          700: "hsl(var(--km0-yellow-700))",
          800: "hsl(var(--km0-yellow-800))",
          900: "hsl(var(--km0-yellow-900))",
        },
        "km0-teal": {
          50:  "hsl(var(--km0-teal-50))",
          100: "hsl(var(--km0-teal-100))",
          200: "hsl(var(--km0-teal-200))",
          300: "hsl(var(--km0-teal-300))",
          400: "hsl(var(--km0-teal-400))",
          500: "hsl(var(--km0-teal-500))",
          600: "hsl(var(--km0-teal-600))",
          700: "hsl(var(--km0-teal-700))",
          800: "hsl(var(--km0-teal-800))",
          900: "hsl(var(--km0-teal-900))",
        },
        "km0-coral": {
          50:  "hsl(var(--km0-coral-50))",
          100: "hsl(var(--km0-coral-100))",
          200: "hsl(var(--km0-coral-200))",
          300: "hsl(var(--km0-coral-300))",
          400: "hsl(var(--km0-coral-400))",
          500: "hsl(var(--km0-coral-500))",
          600: "hsl(var(--km0-coral-600))",
          700: "hsl(var(--km0-coral-700))",
          800: "hsl(var(--km0-coral-800))",
          900: "hsl(var(--km0-coral-900))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
