// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my profile",
  description: "Returns the signed-in user's KM0 Lab profile (name, email, postal code, town).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("first_name,last_name,email,postal_code,town,avatar_url").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/query-events.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var query_events_default = defineTool2({
  name: "query_local_events",
  title: "Query local events",
  description: "Search local events near the signed-in user using the KM0 Lab event-query engine. Uses the user's saved postal code by default; pass postal_code to override.",
  inputSchema: {
    question: z.string().min(1).describe("Natural-language question about local events."),
    postal_code: z.string().optional().describe("Optional 5-digit Spanish postal code. Defaults to the user's profile postal code."),
    limit: z.number().int().min(1).max(50).optional().describe("Max events to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ question, postal_code, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let cp = postal_code;
    if (!cp) {
      const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      });
      const { data: data2 } = await supabase.from("profiles").select("postal_code").eq("user_id", ctx.getUserId()).maybeSingle();
      cp = data2?.postal_code ?? "08001";
    }
    const url = `${process.env.SUPABASE_URL}/functions/v1/event-query`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY}`
      },
      body: JSON.stringify({ pregunta: question, cp_usuario: cp, limit: limit ?? 20, debug: false })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Event API error: ${res.status}` }], isError: true };
    }
    const data = await res.json();
    return {
      content: [{ type: "text", text: data.respuesta_texto ?? "" }],
      structuredContent: { answer: data.respuesta_texto, events: data.eventos ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "itprvihlhgcrajbsbfta";
var mcp_default = defineMcp({
  name: "km0lab-mcp",
  title: "KM0 Lab MCP",
  version: "0.1.0",
  instructions: "Tools for the KM0 Lab local-assistant app. Use `get_profile` to read the signed-in user's profile and `query_local_events` to search local events near them.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, query_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
